# docker-compose.yml

version: "3.9"
services:
  auth-db:
    container_name: auth-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sirius
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: simple_auth
    ports: 
      - '5432:5432'
    volumes:
      - ./simple-node-auth-api-db:/var/lib/postgresql/data

  migration-script:
    build:
      context: ./migration
    depends_on:
      - auth-db
    environment:
      DB_type: pg
      DB_name: simple_auth
      DB_user: sirius
      DB_pass: postgres123
      DB_host: auth-db

  simple-node-auth-api:
    build:
      context: ./api
    restart: always
    depends_on:
      - migration-script
    environment:
      NODE_ENV: production
      SUB_DOMAIN_NAME: client
      DOMAIN_NAME: localhost
      UPLOADED_FILES: /files
      UPLOADED_FILES_FOLDER: uploaded_files
      UPLOADED_PHOTOS: /avatar
      UPLOADED_PHOTOS_FOLDER: uploaded_avatars
      HOST: localhost
      PORT: 3000
      API_VERSION: /api/v1
      SECRET: nikolBoziTxa2021
      EMAIL: avet.sargsyan@yahoo.com
      EMAIL_PASS: sjodiijajlssxbkf
      DB_type: pg
      DB_name: simple_auth
      DB_user: sirius
      DB_pass: postgres123
      DB_host: auth-db
      DB_port: 5432
      # GOOGLE_CLIENTID: 611015742909469
      # GOOGLE_CLIENTSECRET: 757**********************bed
      # GOOGLE_CALLBACKURL: http://localhost:8000/auth/facebook/callback
      # FB_CLIENT_ID: 2081505128657810
      # FB_CLIENT_SECRET: 0d71df36e1a20252c8005d77d2483f98
      # FB_CALLBACK_URL: http://localhost:8080/api/v1/users/auth/facebook/callback
      # BUCKET_NAME: imm-tmp
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
      SLACK_CHANNEL: taxul
    ports:
      - '3000:3000'
    # volumes:
    #   - simple-node-auth-api-db:/var/lib/postgresql/data
# volumes:
#   simple-node-auth-api-db: